name: yhtticket-deployment
services:

  bot:
    # use dockerfile to build image
    entrypoint: ["/run/secrets/secrets2env.sh", "python", "__main__.py"]
    secrets:
      - BOT_TOKEN.env
      - AUTH_USER_IDS.env
      - secrets2env.sh
    container_name: bot
    image: bot
    build: .
    volumes:
      - ./src:/src
      - ./bot_data:/bot_data
    working_dir: /src
    restart: always
    networks:
      - yhtticker-network
    depends_on:
      - redis
      - celery
  
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
      - ./bot_data:/bot_data
    working_dir: /src
    command: celery -A tasks.celery_tasks worker -c 1 --loglevel=INFO 
    restart: always
    networks:
      - yhtticker-network
    # requires redis first
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - yhtticker-network
    restart: always


networks:
  yhtticker-network:
    driver: bridge


secrets:
  BOT_TOKEN.env:
    environment: BOT_TOKEN
  AUTH_USER_IDS.env:
    environment: AUTH_USER_IDS
  secrets2env.sh:
    file: ./secrets2env.sh
  