version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
    - '9000:9000'
    volumes:
    - ./sonar-data/sonarqube_data:/opt/sonarqube/data
    - ./sonar-data/sonarqube_logs:/opt/sonarqube/logs
    - ./sonar-data/sonarqube_extensions:/opt/sonarqube/extensions
    - ./sonar-data/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    environment:
    - sonar.jdbc.url=jdbc:postgresql://db:5432/sonarqube
    - sonar.jdbc.username=sonar
    - sonar.jdbc.password=sonar

  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    - POSTGRES_DB=sonarqube
    volumes:
    - ./sonar-data/postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql_data:





